# Generated by Django 4.1 on 2022-08-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('n_celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('n_celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('n_celular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField()),
                ('n_celular', models.IntegerField()),
            ],
        ),
    ]
