# Generated by Django 4.1 on 2022-08-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_flia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='madre',
            new_name='Familiar',
        ),
        migrations.DeleteModel(
            name='hermano',
        ),
        migrations.DeleteModel(
            name='padre',
        ),
        migrations.DeleteModel(
            name='pareja',
        ),
    ]
