# Generated by Django 4.1 on 2022-08-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_flia', '0002_rename_madre_familiar_delete_hermano_delete_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='vinculo',
            field=models.CharField(default='directo', max_length=100),
            preserve_default=False,
        ),
    ]
